# DROP TABLE users;
# DROP TABLE ads;

USE adllister;

CREATE  TABLE IF NOT EXISTS users(

  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE  TABLE IF NOT EXISTS ads(

  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO users(username,
  email, password
) VALUES ("name", "email@email.com", "1234");

ALTER TABLE ads ADD FOREIGN KEY(user_id) REFERENCES ads(id);

DROP USER 'bubba'@'localhost';
CREATE USER 'bubba'@'localhost' IDENTIFIED BY '';

GRANT ALL ON AdLlister.* TO 'bubba'@'localhost';

INSERT INTO users( email, password)
    VALUES ("email@email.com", "1234");

INSERT INTO ads ( title, description)
VALUES ("this is an test of the emergency alert system", "fuck the commies")

INSERT INTO `ads` (`title`,`description`) VALUES ("velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae","Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu."),("orci quis lectus.","nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse"),("non, luctus","eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique"),("felis orci, adipiscing non, luctus sit","consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue"),("dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit","odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla."),("mauris ipsum porta elit, a feugiat tellus lorem","Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi."),("metus. Aenean","arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula"),("dis parturient montes, nascetur ridiculus mus.","accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate,"),("In tincidunt congue turpis. In condimentum. Donec at arcu.","eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc"),("Fusce aliquet magna a","Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet");
INSERT INTO `ads` (`title`,`description`) VALUES ("natoque penatibus et magnis dis parturient montes,","mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget"),("sem semper erat, in consectetuer ipsum nunc id enim. Curabitur","risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet"),("et, lacinia vitae, sodales at,","lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique"),("vel","odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce"),("vel, vulputate eu, odio. Phasellus at augue id ante","aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In"),("odio. Phasellus at augue","fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit"),("pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero.","mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet"),("ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus","magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque"),("enim. Nunc ut erat. Sed nunc est, mollis non,","mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc"),("lectus. Cum sociis natoque","posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue.");
INSERT INTO `ads` (`title`,`description`) VALUES ("Sed","neque non quam. Pellentesque habitant morbi tristique senectus et netus"),("tortor. Integer aliquam adipiscing","Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl"),("adipiscing ligula. Aenean gravida nunc sed","lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi"),("ac urna. Ut","In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum"),("semper et,","nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu"),("purus. Maecenas libero est, congue a, aliquet vel, vulputate eu,","morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam"),("Proin eget odio. Aliquam vulputate ullamcorper magna.","elit elit fermentum risus, at fringilla purus mauris a nunc. In"),("Mauris blandit","et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed"),("amet, risus. Donec nibh enim, gravida sit amet, dapibus id,","odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus"),("Vivamus molestie dapibus ligula. Aliquam erat","tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas");
INSERT INTO `ads` (`title`,`description`) VALUES ("justo eu arcu. Morbi sit amet massa. Quisque porttitor eros","amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus"),("ultrices.","lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id"),("amet ultricies","ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam"),("pretium et, rutrum non, hendrerit","velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem"),("dolor dolor, tempus non,","aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus."),("Nulla facilisi. Sed neque. Sed eget lacus. Mauris non","neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in"),("montes,","arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae,"),("ut odio vel est tempor","eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero."),("tempor diam dictum sapien. Aenean","vitae risus. Duis a mi fringilla mi lacinia mattis. Integer"),("Fusce","egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet");
INSERT INTO `ads` (`title`,`description`) VALUES ("fames ac turpis","sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque,"),("tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum","Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin"),("Fusce mollis. Duis sit amet","ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt"),("penatibus et magnis dis parturient montes,","condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing"),("Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,","auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec"),("Pellentesque tincidunt tempus","tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing."),("suscipit, est ac","at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum"),("elementum at, egestas a, scelerisque sed, sapien.","pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget"),("cursus et,","dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna."),("lobortis tellus justo","quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris.");
INSERT INTO `ads` (`title`,`description`) VALUES ("vitae sodales nisi","est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus,"),("lobortis tellus justo sit amet nulla. Donec non justo. Proin","Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique"),("per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel","non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit"),("hendrerit neque. In ornare sagittis felis. Donec","lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis"),("amet, risus. Donec nibh enim, gravida","Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie."),("risus.","et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan"),("arcu. Nunc","Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis"),("at risus.","et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus."),("Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere","dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est"),("orci","a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed");
INSERT INTO `ads` (`title`,`description`) VALUES ("Proin vel arcu eu odio","lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut"),("massa non ante bibendum ullamcorper. Duis cursus, diam at","ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec"),("massa.","feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis."),("auctor, nunc nulla","adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor"),("amet","Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio,"),("malesuada vel, convallis in, cursus","Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec"),("nisl","dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac"),("fames ac turpis egestas. Fusce aliquet magna a","eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti"),("scelerisque dui. Suspendisse ac metus vitae velit","massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem"),("dictum placerat, augue. Sed molestie. Sed id risus quis diam","augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris");
INSERT INTO `ads` (`title`,`description`) VALUES ("varius.","lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris"),("turpis nec mauris blandit mattis. Cras eget","sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus"),("tristique","ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy."),("ac mi eleifend egestas. Sed pharetra, felis eget varius","non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,"),("In mi pede, nonummy ut,","est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut"),("mi","vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien."),("felis, adipiscing fringilla, porttitor vulputate, posuere","cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis"),("eu, odio. Phasellus at augue id ante dictum cursus. Nunc","tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi."),("urna. Nunc","magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem"),("felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed","ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper");
INSERT INTO `ads` (`title`,`description`) VALUES ("enim diam vel arcu.","Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus"),("consequat purus. Maecenas libero est, congue a, aliquet vel,","Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui,"),("amet, consectetuer adipiscing elit. Curabitur sed tortor.","lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae,"),("mus. Proin vel nisl.","Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus"),("consectetuer ipsum nunc id","id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum"),("mus. Proin vel","non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris."),("accumsan convallis, ante lectus convallis est, vitae","Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae"),("cursus","massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat"),("erat, eget tincidunt dui augue","amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer"),("lorem","Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum.");
INSERT INTO `ads` (`title`,`description`) VALUES ("dictum augue malesuada malesuada. Integer id magna et ipsum cursus","id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per"),("convallis ligula. Donec luctus","non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris,"),("dui. Suspendisse ac metus vitae velit egestas","dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec,"),("mauris. Morbi non sapien molestie","lectus pede et risus. Quisque libero lacus, varius et, euismod et,"),("tincidunt vehicula risus.","sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi"),("commodo auctor velit. Aliquam nisl. Nulla eu","dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris,"),("tristique senectus et netus et malesuada fames ac turpis","turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales."),("mus. Donec dignissim magna","in faucibus orci luctus et ultrices posuere cubilia Curae; Donec"),("placerat. Cras dictum ultricies ligula. Nullam enim.","lobortis. Class aptent taciti sociosqu ad litora torquent per conubia"),("tristique ac, eleifend vitae,","ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis.");

DELETE FROM ads WHERE id = 1;

INSERT INTO `ads` (`title`,`description`) VALUES ("did this work????????? augue ut lacus. Nulla tincidunt, neque vitae","Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu."),("orci quis lectus.","nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse"),("non, luctus","eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique"),("felis orci, adipiscing non, luctus sit","consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue"),("dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit","odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla."),("mauris ipsum porta elit, a feugiat tellus lorem","Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi."),("metus. Aenean","arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula"),("dis parturient montes, nascetur ridiculus mus.","accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate,"),("In tincidunt congue turpis. In condimentum. Donec at arcu.","eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc"),("Fusce aliquet magna a","Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet");
